### ISSUE TITLE
run_analysis_trajectories.py read_stat_files() emits error with read_stats_detailed function

### ISSUE THREAD

**Issue by heejongkim** [salilab/imp_analysis_tutorial#3]
Hi,

I got some test-drive runs from my own benchmark dataset via modeling.py

However, when i attempt to execute run_analysis_trajectories.py, i repeatedly getting the following error and eventually it failed with get_psi_stats part with "IndexError: list index out of range" because the list is empty.

It seems fine to provide the right traj and stat_files to read_stats_detailed function but
S_score and S_dist are empty list so it causes error with "Get distance fields" and so on.

> Process Process-2:
> Traceback (most recent call last):
>   File "/cm/shared/apps/python-3.7.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/cm/shared/apps/python-3.7.7/lib/python3.7/multiprocessing/process.py", line 99, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/kim/imp_single_node_test/imp_analysis_tutorial/rnapolii_01_50_100/analysis/../../lib/PMI_analysis/pyext/src/analysis_trajectories.py", line 527, in read_traj_info
>     stat_files)
>   File "/home/kim/imp_single_node_test/imp_analysis_tutorial/rnapolii_01_50_100/analysis/../../lib/PMI_analysis/pyext/src/analysis_trajectories.py", line 468, in read_stats_detailed
>     S_dist = S_dist[S_dist[:,0].argsort()]
> IndexError: too many indices for array
> 

Is there a way to take a look at this in a different angle to troubleshoot where it got messed up?
I suspect that it could be the output file itself but I don't have a good understanding to tell whether it's ok or not.

Thanks.

**Comment by heejongkim** [comment]
I will get back to this again once I have no issue with this pol II example as I'm encountering an issue with that as well.
